(autoload 'ell-read-from-file                   "ell" "" nil)
(autoload 'ell-new-cache                        "ell" "" nil)
(autoload 'ell-read-cache-from-file             "ell" "" nil)
(autoload 'ell-write-to-file                    "ell" "" nil)
(autoload 'ell-write-cache-to-file              "ell" "" nil)
(autoload 'ell-packages-list                    "ell" "" nil)
(autoload 'ell-build-packages-list              "ell" "" nil)
(autoload 'ell-sort-by-author                   "ell" "" nil)
(autoload 'ell-mode                             "ell" "" t)
(autoload 'ell-prepare-buffer                   "ell" "" nil)
(autoload 'ell-update-buffer                    "ell" "" nil)
(autoload 'ell-packages                         "ell" "" t)
(autoload 'ell-fix-for-xml-parser-bug           "ell" "" nil)
(provide 'ell-autoloads)
